# Generated by Django 4.2.4 on 2024-03-21 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0012_alter_option_question_alter_question_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
    ]
