# Generated by Django 4.2.4 on 2024-04-27 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='enrollment_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
