# Generated by Django 4.2.4 on 2024-03-13 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subchapter',
            name='teacher',
        ),
    ]
