# Generated by Django 4.2.4 on 2024-04-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_is_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='lesson',
        ),
        migrations.AddField(
            model_name='student',
            name='lesson',
            field=models.ManyToManyField(blank=True, null=True, related_name='students', to='accounts.lesson'),
        ),
    ]
