# Generated by Django 4.2.4 on 2023-10-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_imagestore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagestore',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
