# Generated by Django 4.2.4 on 2024-04-28 20:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_student_lesson_student_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='affiliation',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
