# Generated by Django 4.2.4 on 2023-11-30 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_teacher_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subchapter',
            name='teacher',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher'),
        ),
    ]
