# Generated by Django 4.2.4 on 2024-02-18 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_subchapter_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagePath', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Hotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('yaw', models.FloatField()),
                ('pitch', models.FloatField()),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspots', to='accounts.scene')),
            ],
        ),
    ]
