# Generated by Django 4.2.4 on 2024-02-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_scene_hotspot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotspot',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
