# Generated by Django 4.2.4 on 2024-02-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_hotspot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='id',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
